BP-3190-Add-getActiveSubscriptions
buckaroo-it/BuckarooSDK_Node pull request #33
Opened 2023-11-27 15:26 UTC by Rinor12010

2023-11-27 15:55 UTC, harli91 submitted a review, later dismissed

2023-11-27 15:55 UTC, harli91 commented on src/PaymentMethods/Subscriptions/index.ts
> +        return this.dataRequest();
shouldn't you format the result somehow?

2023-11-29 15:18 UTC, vildanbina commented on src/Services/ActiveSubscriptions.ts
> +        let parseString = require('xml2js').parseString;
`parseString` should be moved inside `typeof xmlData === 'string'` condition

2023-11-29 15:22 UTC, vildanbina requested changes

2023-11-29 15:22 UTC, vildanbina commented on src/Services/ActiveSubscriptions.ts
> +                activeSubscriptions = result['ServiceCurrencies'].map((service:any) => {
`result['ServiceCurrencies']` is causing an error. I believe it should be `result['ArrayOfServiceCurrencies']['ServiceCurrencies']` instead

2023-11-30 11:56 UTC, vildanbina approved these changes

2023-11-30 13:54 UTC, merged